#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["Pillow"]
# ///
"""
Overlay story text onto a children's book page image.

One box model: panel = text block (at the configured font size) + padding. The
text pushes the panel from the inside — panel height is derived from content,
never configured. Font size shrinks in exactly one circumstance: the panel
would otherwise exceed `max_panel_fraction` of the page height. That is a
last-resort overflow guard, not a layout mechanism. See docs/text-fitting.md.

Two surfaces (select with --text-page), differing only in growth anchor —
where the panel is pinned, not how it is sized:

Band mode (default) — overlay mode / native-mode covers:
  uv run overlay_text.py --image page.png --text "Once upon a time..." \
      --placement bottom --out page-final.png [--font reader|display] [--color dark|light]

Text-page mode (--text-page) — long story mode body pages:
  uv run overlay_text.py --image text-bg.png --text "Long story text..." \
      --text-page --out page-text.png
  # Crop the background to the matching art page's dimensions:
  uv run overlay_text.py --image text-bg.png --text "..." \
      --text-page --canvas-from art-page.png --out page-text.png

In text-page mode --image is a purpose-made background (generated by the render
stage with a reserved central text section); the text sits on a centered feathered
semi-transparent panel. No blur or wash is applied to the background.

All sizes (font, padding, radius, feather) are authored as pixels at a declared
`reference_size` and scaled by one uniform factor — min(page_w, page_h) /
reference_size — at composite time, so a 1K OpenAI-fallback page, a 2K Gemini
page, and a 4K upscaled page all compose identically. Override the reference-unit
defaults via --font-size/--pad-h/--pad-v/--radius/--feather/--max-panel-fraction/
--reference-size, or programmatically via the `layout=` LayoutSettings argument.

Optional deterministic page frame (PER-105, --frame / `border=` BorderSettings):
composites a margin of a fixed colour around the artwork, with a corner radius on
the artwork itself and an optional drop shadow. The artwork is downscaled to fit
inside the resulting inset "art rect" — nothing is cropped. All panel/text
geometry re-bases onto that art rect instead of the full canvas, so the text
band never spills onto the margin. Omit --frame (border=None, the default) for
today's full-bleed behaviour, byte-identical to pre-PER-105 output. See
docs/page-frame.md.

Importable:
  from overlay_text import overlay, text_page
  overlay("page.png", "Once upon a time...", "bottom", "page-final.png")
  text_page("art.png", "Long text here.", "page-text.png")
"""

from __future__ import annotations
import argparse
import math
import sys
from dataclasses import dataclass, replace
from pathlib import Path

from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

SKILL_DIR = Path(__file__).parent.parent
FONTS = {
    "reader": SKILL_DIR / "assets" / "fonts" / "Andika-Regular.ttf",
    "display": SKILL_DIR / "assets" / "fonts" / "PatrickHand-Regular.ttf",
}

# ---- Reference-unit layout defaults ----------------------------------------------
# Every length below is authored as pixels *at this reference size* and scaled by
# min(page_w, page_h) / reference_size at composite time — one uniform scalar, so
# type and padding grow together and an aspect-ratio change never changes type
# size. See docs/text-fitting.md.
REFERENCE_SIZE = 2048
DEFAULT_FONT_SIZE = 48          # measured to keep a 200-word page (STYLE_PRIMER's
                                 # documented ceiling) well inside max_panel_fraction
DEFAULT_MIN_FONT_SIZE = 22
DEFAULT_PAD_H = 40              # gap between text and panel's left/right edge
DEFAULT_PAD_V = 48              # gap between text block and panel's top/bottom edge
DEFAULT_RADIUS = 36
DEFAULT_FEATHER = 14            # 0 = hard edge
DEFAULT_MAX_PANEL_FRACTION = 0.9
LINE_LEADING = 8                # extra px of line spacing beyond the glyph bbox

# Horizontal text margin as fraction of image width — already resolution-
# independent, so it is not part of the reference-unit `layout` settings.
H_PAD_FRACTION = 0.05
# Top-placement gap from the frame, as fraction of image height. This is
# *placement*, not the boundary — it stays a module constant, out of `layout`.
# Deriving it from max_panel_fraction would couple two unrelated knobs and
# re-flow every top-placed page for no reason.
EDGE_MARGIN_FRACTION = 0.04
# Background panel alpha (0=transparent, 255=opaque) — unitless 0-255, nothing
# to scale, so it also stays outside `layout`.
BOX_ALPHA = 205

# ---- Deterministic page frame (PER-105) -------------------------------------------
# Reference-unit lengths (same reference_size as `layout` — border does not
# declare its own; one unit baseline per book). Presence of a BorderSettings
# instance (border=None is the off switch) is what turns the frame on; these
# are only the values it uses once on.
DEFAULT_BORDER_WIDTH = 64
DEFAULT_BORDER_COLOR = "#FFFFFF"
DEFAULT_BORDER_RADIUS = 48
DEFAULT_SHADOW_OFFSET = 12
DEFAULT_SHADOW_BLUR = 24
DEFAULT_SHADOW_OPACITY = 0.25


def _scale_len(v: float, scale: float, min_val: int = 0) -> int:
    return max(min_val, round(v * scale))


@dataclass(frozen=True)
class LayoutSettings:
    """The one box model's tunables, authored as pixels at `reference_size`
    (`max_panel_fraction` is already a fraction). `.scaled()` converts every
    length to actual page pixels via one uniform scalar. See docs/text-fitting.md.
    """

    reference_size: int = REFERENCE_SIZE
    font_size: int = DEFAULT_FONT_SIZE
    min_font_size: int = DEFAULT_MIN_FONT_SIZE
    pad_h: int = DEFAULT_PAD_H
    pad_v: int = DEFAULT_PAD_V
    radius: int = DEFAULT_RADIUS
    feather: int = DEFAULT_FEATHER
    max_panel_fraction: float = DEFAULT_MAX_PANEL_FRACTION

    def scaled(self, w: int, h: int) -> "LayoutSettings":
        """Return a copy with every reference-unit length scaled to (w, h).

        One uniform scalar for every length (min(w, h) / reference_size), so
        type and padding scale together and an aspect-ratio change never
        changes type size. font_size/min_font_size are floored at 1px (a 0px
        font crashes Pillow); feather has no such floor, so --feather 0 stays
        a hard edge at any resolution.
        """
        scale = min(w, h) / self.reference_size
        return replace(
            self,
            font_size=_scale_len(self.font_size, scale, min_val=1),
            min_font_size=_scale_len(self.min_font_size, scale, min_val=1),
            pad_h=_scale_len(self.pad_h, scale),
            pad_v=_scale_len(self.pad_v, scale),
            radius=_scale_len(self.radius, scale),
            feather=_scale_len(self.feather, scale),
        )


@dataclass(frozen=True)
class ShadowSettings:
    """Drop-shadow tunables, reference-unit px (opacity is already a fraction).
    Only meaningful when nested inside a BorderSettings — there is no shadow
    without a frame to cast it."""

    offset: int = DEFAULT_SHADOW_OFFSET
    blur: int = DEFAULT_SHADOW_BLUR
    opacity: float = DEFAULT_SHADOW_OPACITY


@dataclass(frozen=True)
class BorderSettings:
    """PER-105's deterministic page frame. Reference-unit px, scaled by the same
    uniform factor as LayoutSettings — `.scaled()` takes the reference_size
    explicitly (border has none of its own; it shares the book's `layout`
    baseline). `shadow=None` (the default) means no drop shadow at all, not a
    zero-opacity one.
    """

    width: int = DEFAULT_BORDER_WIDTH
    color: str = DEFAULT_BORDER_COLOR
    radius: int = DEFAULT_BORDER_RADIUS
    shadow: ShadowSettings | None = None

    def scaled(self, w: int, h: int, reference_size: int) -> "BorderSettings":
        scale = min(w, h) / reference_size
        new_shadow = None
        if self.shadow is not None:
            new_shadow = replace(
                self.shadow,
                offset=_scale_len(self.shadow.offset, scale),
                blur=_scale_len(self.shadow.blur, scale),
                # opacity is already a 0-1 fraction — nothing to scale.
            )
        return replace(
            self,
            width=_scale_len(self.width, scale),
            radius=_scale_len(self.radius, scale),
            shadow=new_shadow,
        )


def _hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    s = hex_color.lstrip("#")
    return (int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16))


def art_rect(w: int, h: int, border: BorderSettings | None) -> tuple[int, int, int, int]:
    """The (x0, y0, x1, y1) rectangle the artwork occupies inside a w x h canvas.

    `border` must already be `.scaled()` to (w, h) — this function does no unit
    conversion. None, or a non-positive width, returns the full canvas
    (0, 0, w, h) — today's full-bleed behaviour, byte-identical. The margin
    never collapses the art to nothing, even at a pathologically large width.
    """
    if border is None or border.width <= 0:
        return (0, 0, w, h)
    m = min(border.width, (min(w, h) - 1) // 2)
    return (m, m, w - m, h - m)


def frame_canvas(
    art: Image.Image,
    w: int,
    h: int,
    rect: tuple[int, int, int, int],
    border: BorderSettings,
) -> Image.Image:
    """Composite `art` (already exactly rect-sized — resize/crop is the
    caller's job, since art pages and text pages fit differently) onto a
    w x h canvas: a flat margin in border.color, an optional soft drop
    shadow, and the artwork itself with rounded corners.

    `border` must already be `.scaled()` to (w, h).
    """
    ax0, ay0, ax1, ay1 = rect
    canvas = Image.new("RGBA", (w, h), _hex_to_rgb(border.color) + (255,))

    if border.shadow is not None:
        sh = border.shadow
        shadow_rect = (ax0 + sh.offset, ay0 + sh.offset, ax1 + sh.offset, ay1 + sh.offset)
        shadow_mask = _panel_mask(
            w, h, shadow_rect, border.radius, int(round(255 * sh.opacity)), sh.blur,
        )
        shadow_layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        shadow_layer.putalpha(shadow_mask)
        canvas = Image.alpha_composite(canvas, shadow_layer)

    art_mask = _panel_mask(w, h, rect, border.radius, 255, feather=0)
    art_layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    art_layer.paste(art.convert("RGBA"), (ax0, ay0))
    art_layer.putalpha(art_mask)
    return Image.alpha_composite(canvas, art_layer)


def _normalize_family(name: str) -> str:
    """Lowercase, keep only alphanumerics — so 'Patrick Hand' == 'PatrickHand'."""
    return "".join(c for c in name.lower() if c.isalnum())


def _bundled_font_path(name: str) -> Path | None:
    """Match a requested family name against a bundled .ttf in assets/fonts/.

    Bundled OFL fonts always win over a same-named system font, so 'Andika' /
    'Patrick Hand' resolve to the shipped files regardless of what's installed.
    """
    target = _normalize_family(name)
    fonts_dir = SKILL_DIR / "assets" / "fonts"
    for ttf in sorted(fonts_dir.glob("*.ttf")):
        stem = ttf.stem.lower().removesuffix("-regular")
        if _normalize_family(stem) == target:
            return ttf
    return None


def _resolve_font_ref(role: str, name: str | None = None) -> str:
    """Resolve a role + optional family name to a truetype reference (path or system name).

    Resolution order when an explicit family `name` is given:
      1. bundled asset matching the name (assets/fonts/)
      2. system-installed font (PIL searches OS font dirs by family name)
      3. bundled default for the role (reader -> Andika, display -> PatrickHand) + warning

    Rendering is rasterized to pixels, so using a system font (e.g. Arial) does not
    redistribute the font file. Unresolvable names never crash the render. Resolved
    once per overlay so the not-found warning fires at most once.
    """
    if name:
        bundled = _bundled_font_path(name)
        if bundled is not None:
            return str(bundled)
        for candidate in (name, f"{name}.ttf"):
            try:
                ImageFont.truetype(candidate, 12)  # probe OS font dirs
                return candidate
            except OSError:
                continue
        print(
            f"Warning: font {name!r} not found (no bundled asset, not a system font); "
            f"falling back to the bundled {role!r} font.",
            file=sys.stderr,
        )
    return str(FONTS.get(role, FONTS["reader"]))


def _load_font(font_ref: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(font_ref, size)


def _wrap_paragraph(text: str, font: ImageFont.FreeTypeFont, max_width: int, draw: ImageDraw.ImageDraw) -> list[str]:
    """Greedy word-wrap of a single paragraph (no newlines) to max_width."""
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = (current + " " + word).strip()
        bbox = draw.textbbox((0, 0), candidate, font=font)
        if bbox[2] - bbox[0] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _word_wrap(text: str, font: ImageFont.FreeTypeFont, max_width: int, draw: ImageDraw.ImageDraw) -> list[str]:
    """Wrap story text to max_width, preserving the author's line structure.

    Every newline is a hard break, so a dialogue line stays on its own line; a blank
    line additionally yields an empty output line, keeping paragraphs visually apart.
    Runs of blank lines collapse to one spacer, and spacers never lead or trail the
    block. The returned list may therefore contain "" entries — callers must advance
    by one line height for them without drawing anything.
    """
    lines: list[str] = []
    for block in text.split("\n"):
        block = block.strip()
        if not block:
            if lines and lines[-1] != "":
                lines.append("")
            continue
        lines.extend(_wrap_paragraph(block, font, max_width, draw))
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def measure_text_block(
    text: str,
    font_ref: str,
    w: int,
    h: int,
    lay: LayoutSettings,
    max_box_h: int,
    max_text_w: int | None = None,
) -> tuple[int, list[str], int, int, int]:
    """Fit text to one panel sized from its own content.

    panel = text block (at lay.font_size) + padding — the box is derived from
    content, never configured. Font size shrinks in exactly one circumstance:
    the panel would otherwise exceed max_box_h, down to lay.min_font_size. That
    is a last-resort overflow guard, not a layout mechanism.

    `lay` must already be scaled to (w, h) via LayoutSettings.scaled() — this
    function does no unit conversion of its own. w, h are the CANVAS
    dimensions (used only to derive the leading scale factor) — pass
    max_text_w explicitly when the text column is narrower than the canvas
    (PER-105's bordered art rect); omitted, it defaults to w's own
    H_PAD_FRACTION inset, i.e. today's full-bleed behaviour.

    Returns (font_size, lines, line_h, box_h, dropped). Both the boundary check
    here and the draw loop in _compose() consume this single measurement —
    measuring the fit and the draw with two different formulas (as the old
    band/text-page fit loops did) is exactly the bug this replaces. `dropped`
    is the number of wrapped lines that don't fit even at lay.min_font_size
    (0 in the ordinary case) — the caller is responsible for reporting it.
    """
    scale = min(w, h) / lay.reference_size
    leading = _scale_len(LINE_LEADING, scale, min_val=1)
    if max_text_w is None:
        max_text_w = int(w * (1 - 2 * H_PAD_FRACTION))
    dummy = ImageDraw.Draw(Image.new("RGBA", (w, h)))

    size = lay.font_size
    while True:
        font = _load_font(font_ref, size)
        lines = _word_wrap(text, font, max_text_w, dummy)
        bbox = dummy.textbbox((0, 0), "Ag", font=font)
        line_h = bbox[3] - bbox[1] + leading
        box_h = len(lines) * line_h + 2 * lay.pad_v
        if box_h <= max_box_h or size <= lay.min_font_size:
            break
        size = max(lay.min_font_size, size - 2)

    dropped = 0
    if box_h > max_box_h and line_h > 0:
        avail = max(0, max_box_h - 2 * lay.pad_v)
        fit_lines = avail // line_h
        if fit_lines < len(lines):
            dropped = len(lines) - fit_lines
            lines = lines[:fit_lines]
            box_h = len(lines) * line_h + 2 * lay.pad_v

    return size, lines, line_h, box_h, dropped


def _panel_mask(
    w: int, h: int, box: tuple[int, int, int, int], radius: int, alpha: int, feather: int
) -> Image.Image:
    """Build a full-canvas alpha mask with one blurred rounded rect painted on it.

    The blur is applied to the mask only, so the panel fades softly into the
    image instead of ending at a hard edge, while text (composited separately)
    stays crisp.
    """
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).rounded_rectangle(box, radius=radius, fill=alpha)
    if feather > 0:
        mask = mask.filter(ImageFilter.GaussianBlur(feather))
    return mask


def _draw_text_lines(
    w: int,
    h: int,
    lines: list[str],
    font: ImageFont.FreeTypeFont,
    line_h: int,
    start_y: int,
    h_pad: int,
    max_text_w: int,
    align: str,
    color: str,
    x_origin: int = 0,
    region_w: int | None = None,
) -> Image.Image:
    """Draw every line handed to it onto its own transparent layer — no clipping
    loop. Any truncation was already decided once, by measure_text_block().

    All three alignments are defined against the text column [h_pad, w - h_pad],
    not raw canvas width, so 'right' lands its edge at w - h_pad regardless of
    padding. x_origin/region_w (PER-105) shift that column to a bordered art
    rect: x_origin is the rect's left edge, region_w its width. Defaults
    (x_origin=0, region_w=w) reproduce the pre-PER-105 formula byte-for-byte.
    """
    if region_w is None:
        region_w = w
    text_layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(text_layer)
    text_color = (30, 30, 30, 255) if color == "dark" else (245, 245, 245, 255)
    y = start_y
    for line in lines:
        # "" is a paragraph spacer: it occupies a line but draws nothing.
        if line:
            line_w = draw.textlength(line, font=font)
            if align == "center":
                x = x_origin + int(h_pad + (max_text_w - line_w) / 2)
            elif align == "right":
                x = x_origin + int(region_w - h_pad - line_w)
            else:
                x = x_origin + h_pad
            draw.text((x, y), line, font=font, fill=text_color)
        y += line_h
    return text_layer


def _compose(
    art: Image.Image,
    canvas_w: int,
    canvas_h: int,
    text: str,
    out_path: Path,
    font: str,
    font_name: str | None,
    color: str,
    box_alpha: int,
    align: str,
    layout: LayoutSettings,
    border: BorderSettings | None,
    anchor: str,
    label: str,
) -> Path:
    """Shared frame-panel-and-text compositor for both surfaces.

    `art` is the artwork; its own size may be the full canvas (border=None) or
    already exactly the art-rect size a caller pre-fit it to (PER-105's
    caller-owned fit policy — see overlay()/text_page()). `canvas_w`/`canvas_h`
    are the FINAL image dimensions, which never change: a border shrinks where
    the art sits, not the page size.

    anchor: 'top' | 'bottom' (band mode) | 'center' (text-page mode) — which
    edge the panel is pinned to, and the only thing that legitimately differs
    between band mode and text-page mode. See docs/text-fitting.md "Growth
    anchors" and docs/page-frame.md.
    """
    w, h = canvas_w, canvas_h
    lay = layout.scaled(w, h)
    scale = min(w, h) / lay.reference_size
    scaled_border = border.scaled(w, h, lay.reference_size) if border is not None else None
    ax0, ay0, ax1, ay1 = art_rect(w, h, scaled_border)
    aw, ah = ax1 - ax0, ay1 - ay0
    bordered = scaled_border is not None and (aw, ah) != (w, h)

    # Frame first (PER-105) — before the empty-text early return, so a
    # frame-only page (native, long-body art: overlay() called with text="")
    # still gets composited. border=None is the identity path: `canvas` is
    # exactly `art`, untouched — byte-identical to pre-PER-105 output.
    if bordered:
        art_for_canvas = art if art.size == (aw, ah) else art.resize((aw, ah), Image.LANCZOS)
        canvas = frame_canvas(art_for_canvas, w, h, (ax0, ay0, ax1, ay1), scaled_border)
    else:
        canvas = art.convert("RGBA")

    if not text.strip():
        canvas.convert("RGB").save(out_path)
        return out_path

    font_ref = _resolve_font_ref(font, font_name)

    edge_margin = int(ah * EDGE_MARGIN_FRACTION)
    max_box_h = int(ah * lay.max_panel_fraction)
    if anchor == "top":
        # A centred text page runs out of room top and bottom simultaneously; a
        # bottom-anchored band has one edge pinned and grows until it reaches
        # the top margin. Top placement is the one anchor with a second,
        # tighter ceiling: it must also leave the matching gap below.
        max_box_h = min(max_box_h, ah - 2 * edge_margin)

    h_pad = int(aw * H_PAD_FRACTION)
    max_text_w = int(aw * (1 - 2 * H_PAD_FRACTION))
    size, lines, line_h, box_h, dropped = measure_text_block(
        text, font_ref, w, h, lay, max_box_h, max_text_w=max_text_w,
    )
    font_obj = _load_font(font_ref, size)

    box_x0 = ax0 + h_pad - lay.pad_h
    box_x1 = ax1 - h_pad + lay.pad_h

    # Bottom placement anchors the panel flush to the art's bottom edge (no
    # gap); it is drawn past that edge so its rounded corners fall off-frame
    # and the bottom reads as a straight edge. Top keeps the edge margin.
    # Center floats with all four corners rounded. All three anchor to the
    # ART rect, not the canvas — with no border ax0=ay0=0 and aw=w, ah=h, so
    # this reproduces the pre-PER-105 canvas-relative formulas exactly.
    if anchor == "top":
        box_y0 = ay0 + edge_margin
        panel_y1 = box_y0 + box_h
    elif anchor == "bottom":
        box_y0 = ay1 - box_h
        panel_y1 = ay1 + lay.radius
    else:  # center
        box_y0 = ay0 + (ah - box_h) // 2
        panel_y1 = box_y0 + box_h

    panel_mask = _panel_mask(w, h, (box_x0, box_y0, box_x1, panel_y1), lay.radius, box_alpha, lay.feather)
    if bordered:
        # Clip the panel to the artwork's own rounded shape so the band never
        # spills onto the margin (the defect this whole change exists to fix).
        art_mask = _panel_mask(w, h, (ax0, ay0, ax1, ay1), scaled_border.radius, 255, feather=0)
        panel_mask = ImageChops.multiply(panel_mask, art_mask)
    panel_rgb = (255, 255, 255) if color == "dark" else (30, 30, 30)
    panel = Image.new("RGBA", (w, h), panel_rgb + (0,))
    panel.putalpha(panel_mask)
    canvas = Image.alpha_composite(canvas, panel)

    text_layer = _draw_text_lines(
        w, h, lines, font_obj, line_h, box_y0 + lay.pad_v, h_pad, max_text_w, align, color,
        x_origin=ax0, region_w=aw,
    )
    composed = Image.alpha_composite(canvas, text_layer)
    composed.convert("RGB").save(out_path)

    if dropped:
        # Warn and composite — never block a book assembly over one over-long
        # page. Stable "TEXT-OVERFLOW:" prefix so callers can grep stderr for it.
        print(
            f"TEXT-OVERFLOW: {label} — configured {lay.font_size}px, used {size}px, "
            f"{dropped} line(s) dropped",
            file=sys.stderr,
        )

    return out_path


def overlay(
    image_path: str | Path,
    text: str,
    placement: str,
    out_path: str | Path,
    font: str = "reader",
    color: str = "dark",
    box_alpha: int = BOX_ALPHA,
    font_name: str | None = None,
    align: str = "left",
    layout: LayoutSettings | None = None,
    border: BorderSettings | None = None,
) -> Path:
    """
    Composite text onto an image in the top or bottom zone.

    The panel is sized from its content: panel = text block (at
    layout.font_size) + padding. Font size shrinks only if the panel would
    otherwise exceed layout.max_panel_fraction of the page — a last-resort
    overflow guard, not a layout mechanism. See docs/text-fitting.md.

    An empty `text` still runs the border/frame step (if `border` is set) —
    that's how native-mode and long-body-art pages, which have no text panel
    of their own, get framed: call this with text="" (see docs/page-frame.md).

    Args:
        image_path: Source PNG/JPG.
        text: Story text. Empty string = no text panel (frame, if any, still applies).
        placement: 'top' or 'bottom'.
        out_path: Destination path.
        font: role 'reader' or 'display' — selects the bundled fallback font.
        color: 'dark' (near-black text on light panel) or 'light' (near-white text on dark
            panel). The semi-transparent panel behind the text adapts its base colour to
            match so the text stays legible.
        font_name: optional explicit family name (e.g. 'Arial'); resolved via bundled
            asset -> system font -> bundled role fallback. None = use the role font.
        align: 'left' (default), 'center', or 'right' — horizontal alignment of each line.
        layout: LayoutSettings overriding the reference-unit defaults. None = defaults.
        border: BorderSettings for a deterministic margin/frame (PER-105). None (default)
            = full-bleed, byte-identical to pre-PER-105 output.

    Returns:
        Path to written file.
    """
    out_path = Path(out_path)
    image_path = Path(image_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(image_path).convert("RGBA")
    w, h = img.size
    anchor = "top" if placement == "top" else "bottom"
    return _compose(
        img, w, h, text, out_path, font, font_name, color, box_alpha, align,
        layout or LayoutSettings(), border, anchor, out_path.name,
    )


def text_page(
    image_path: str | Path,
    text: str,
    out_path: str | Path,
    font: str = "reader",
    color: str = "dark",
    box_alpha: int = BOX_ALPHA,
    font_name: str | None = None,
    align: str = "left",
    canvas_from: str | Path | None = None,
    layout: LayoutSettings | None = None,
    border: BorderSettings | None = None,
) -> Path:
    """
    Render a full text page for long story mode.

    image_path is a purpose-made background (generated by the render stage with a
    reserved low-detail central section); it is used as-is — no blur, no wash. When
    canvas_from is set, the page canvas matches the canvas_from image's dimensions
    (so the text page always matches its art page), and the background is
    scale-to-cover + center-cropped to fill the ART rect within that canvas — the
    same rect a border (if set) insets the artwork into on every other surface, so
    text pages get exactly one resample no matter whether a border is set (PER-105:
    cropping straight to the art rect avoids compositing a border on top of an
    already-full-canvas crop, which would resample twice).

    Text sits on a vertically centered, feathered semi-transparent panel, sized
    from its own content exactly as overlay() sizes a band — both surfaces
    share the one box model (see _compose()), differing only in growth anchor.

    Args:
        image_path: The background image.
        text: Story text. Empty string = plain background, no panel.
        out_path: Destination path.
        font: role 'reader' or 'display'.
        color: 'dark' (near-black text on light panel) or 'light' (near-white text on dark
            panel). The semi-transparent panel behind the text adapts its base colour.
        box_alpha: Panel opacity 0-255.
        font_name: Explicit font family; resolved via bundled asset -> system font -> fallback.
        align: 'left', 'center', or 'right'.
        canvas_from: When set, open this image to get target (W, H); scale-crop image_path to fit.
        layout: LayoutSettings overriding the reference-unit defaults. None = defaults.
        border: BorderSettings for a deterministic margin/frame (PER-105). None (default)
            = full-bleed, byte-identical to pre-PER-105 output.

    Returns:
        Path to written file.
    """
    out_path = Path(out_path)
    image_path = Path(image_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(image_path).convert("RGBA")
    w, h = img.size

    if canvas_from is not None:
        ref = Image.open(canvas_from)
        tw, th = ref.size
    else:
        tw, th = w, h

    lay = layout or LayoutSettings()
    scaled_border = border.scaled(tw, th, lay.reference_size) if border is not None else None
    ax0, ay0, ax1, ay1 = art_rect(tw, th, scaled_border)
    aw, ah = ax1 - ax0, ay1 - ay0

    if canvas_from is not None or scaled_border is not None:
        # Scale-to-cover + center-crop the background to the ART rect's dims
        # (aw, ah) — with no border and no canvas_from override, aw==w and
        # ah==h, so this branch is simply never entered and img is used as-is,
        # exactly as before PER-105.
        scale = max(aw / w, ah / h)
        new_w = math.ceil(w * scale)
        new_h = math.ceil(h * scale)
        img = img.resize((new_w, new_h), Image.LANCZOS)
        x0 = (new_w - aw) // 2
        y0 = (new_h - ah) // 2
        img = img.crop((x0, y0, x0 + aw, y0 + ah))

    return _compose(
        img, tw, th, text, out_path, font, font_name, color, box_alpha, align,
        lay, border, "center", out_path.name,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Overlay story text onto a page image.")
    parser.add_argument("--image", required=True, help="Source image path")
    parser.add_argument("--text", required=True, help="Text to overlay")
    parser.add_argument("--placement", choices=["top", "bottom"], default="bottom")
    parser.add_argument("--out", required=True, help="Output image path")
    parser.add_argument("--font", choices=["reader", "display"], default="reader",
                        help="Font role; selects the bundled fallback font")
    parser.add_argument("--font-name", default=None,
                        help="Explicit font family (e.g. 'Arial'); resolved via bundled asset "
                             "-> system font -> bundled role fallback")
    parser.add_argument("--color", choices=["dark", "light"], default="dark")
    parser.add_argument("--align", choices=["left", "center", "right"], default="left",
                        help="Horizontal text alignment (default left)")
    parser.add_argument("--box-alpha", type=int, default=BOX_ALPHA,
                        help=f"Panel opacity 0-255 (default {BOX_ALPHA}; lower = more transparent)")
    # Layout — the one box model's reference-unit settings (see docs/text-fitting.md).
    # All are pixels at --reference-size, scaled by min(page_w, page_h) / reference-size
    # at composite time; --max-panel-fraction is already a fraction.
    parser.add_argument("--reference-size", type=int, default=REFERENCE_SIZE,
                        help=f"Declared reference size in px (default {REFERENCE_SIZE}); "
                             "every other layout flag is authored at this size")
    parser.add_argument("--font-size", type=int, default=DEFAULT_FONT_SIZE,
                        help=f"Font size at --reference-size (default {DEFAULT_FONT_SIZE}px)")
    parser.add_argument("--min-font-size", type=int, default=DEFAULT_MIN_FONT_SIZE,
                        help=f"Overflow-guard floor at --reference-size (default {DEFAULT_MIN_FONT_SIZE}px)")
    parser.add_argument("--pad-h", type=int, default=DEFAULT_PAD_H,
                        help=f"Panel padding left/right at --reference-size (default {DEFAULT_PAD_H}px)")
    parser.add_argument("--pad-v", type=int, default=DEFAULT_PAD_V,
                        help=f"Panel padding top/bottom at --reference-size (default {DEFAULT_PAD_V}px)")
    parser.add_argument("--radius", type=int, default=DEFAULT_RADIUS,
                        help=f"Panel corner radius at --reference-size (default {DEFAULT_RADIUS}px)")
    parser.add_argument("--feather", type=int, default=DEFAULT_FEATHER,
                        help=f"Edge blur radius at --reference-size (default {DEFAULT_FEATHER}px; 0 = hard edge)")
    parser.add_argument("--max-panel-fraction", type=float, default=DEFAULT_MAX_PANEL_FRACTION,
                        help=f"Boundary: most of the page height a panel may cover before the "
                             f"overflow guard shrinks the font (default {DEFAULT_MAX_PANEL_FRACTION})")
    # Long story mode — text-page rendering.
    parser.add_argument("--text-page", action="store_true",
                        help="Render a text-only page (long story mode): centered panel over a "
                             "purpose-made background image (used as-is, no blur/wash). "
                             "Ignores --placement.")
    parser.add_argument("--canvas-from", default=None, metavar="PATH",
                        help="(--text-page only) Open this image to get target W×H; scale-crop "
                             "--image to those dims so text page matches art page dimensions.")
    # Deterministic page frame (PER-105). --frame is the on/off switch — the
    # individual --border-*/--shadow-* flags only matter alongside it, and
    # default to None (not a numeric default) so an omitted flag falls through
    # to overlay_text.py's own DEFAULT_* constant, exactly like the layout
    # flags above. Omitting --frame entirely reproduces pre-PER-105 full-bleed
    # output byte-for-byte. See docs/page-frame.md.
    parser.add_argument("--frame", action="store_true",
                        help="Composite a deterministic margin/border frame around the "
                             "artwork instead of full-bleed (default: no frame).")
    parser.add_argument("--border-width", type=int, default=None,
                        help=f"Margin width at --reference-size (--frame only; "
                             f"default {DEFAULT_BORDER_WIDTH}px)")
    parser.add_argument("--border-color", default=None,
                        help=f"Margin color as #RRGGBB (--frame only; default {DEFAULT_BORDER_COLOR})")
    parser.add_argument("--border-radius", type=int, default=None,
                        help=f"Artwork corner radius at --reference-size (--frame only; "
                             f"default {DEFAULT_BORDER_RADIUS}px)")
    parser.add_argument("--shadow", action="store_true",
                        help="Add a drop shadow under the artwork (--frame only).")
    parser.add_argument("--shadow-offset", type=int, default=None,
                        help=f"Shadow offset at --reference-size (--shadow only; "
                             f"default {DEFAULT_SHADOW_OFFSET}px)")
    parser.add_argument("--shadow-blur", type=int, default=None,
                        help=f"Shadow blur radius at --reference-size (--shadow only; "
                             f"default {DEFAULT_SHADOW_BLUR}px)")
    parser.add_argument("--shadow-opacity", type=float, default=None,
                        help=f"Shadow opacity 0-1 (--shadow only; default {DEFAULT_SHADOW_OPACITY})")
    args = parser.parse_args()

    layout = LayoutSettings(
        reference_size=args.reference_size,
        font_size=args.font_size,
        min_font_size=args.min_font_size,
        pad_h=args.pad_h,
        pad_v=args.pad_v,
        radius=args.radius,
        feather=args.feather,
        max_panel_fraction=args.max_panel_fraction,
    )

    border = None
    if args.frame:
        shadow = None
        if args.shadow:
            shadow = ShadowSettings(
                offset=args.shadow_offset if args.shadow_offset is not None else DEFAULT_SHADOW_OFFSET,
                blur=args.shadow_blur if args.shadow_blur is not None else DEFAULT_SHADOW_BLUR,
                opacity=args.shadow_opacity if args.shadow_opacity is not None else DEFAULT_SHADOW_OPACITY,
            )
        border = BorderSettings(
            width=args.border_width if args.border_width is not None else DEFAULT_BORDER_WIDTH,
            color=args.border_color if args.border_color is not None else DEFAULT_BORDER_COLOR,
            radius=args.border_radius if args.border_radius is not None else DEFAULT_BORDER_RADIUS,
            shadow=shadow,
        )

    if args.text_page:
        result = text_page(
            args.image, args.text, args.out, args.font, args.color,
            box_alpha=args.box_alpha, font_name=args.font_name,
            align=args.align, canvas_from=args.canvas_from, layout=layout, border=border,
        )
    else:
        result = overlay(
            args.image, args.text, args.placement, args.out, args.font, args.color,
            box_alpha=args.box_alpha, font_name=args.font_name,
            align=args.align, layout=layout, border=border,
        )
    print(f"Saved: {result}")


if __name__ == "__main__":
    main()
