#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["Pillow"]
# ///
"""
Overlay story text onto a children's book page image.

One box model: panel = text block (at the configured font size) + padding. The
text pushes the panel from the inside — panel height is derived from content,
never configured. Font size shrinks in exactly one circumstance: the panel
would otherwise exceed `max_panel_fraction` of the page height. That is a
last-resort overflow guard, not a layout mechanism. See docs/text-fitting.md.

Two surfaces (select with --text-page), differing only in growth anchor —
where the panel is pinned, not how it is sized:

Band mode (default) — overlay mode / native-mode covers:
  uv run overlay_text.py --image page.png --text "Once upon a time..." \
      --placement bottom --out page-final.png [--font reader|display] [--color dark|light]

Text-page mode (--text-page) — long story mode body pages:
  uv run overlay_text.py --image text-bg.png --text "Long story text..." \
      --text-page --out page-text.png
  # Crop the background to the matching art page's dimensions:
  uv run overlay_text.py --image text-bg.png --text "..." \
      --text-page --canvas-from art-page.png --out page-text.png

In text-page mode --image is a purpose-made background (generated by the render
stage with a reserved central text section); the text sits on a centered feathered
semi-transparent panel. No blur or wash is applied to the background.

All sizes (font, padding, radius, feather) are authored as pixels at a declared
`reference_size` and scaled by one uniform factor — min(page_w, page_h) /
reference_size — at composite time, so a 1K OpenAI-fallback page, a 2K Gemini
page, and a 4K upscaled page all compose identically. Override the reference-unit
defaults via --font-size/--pad-h/--pad-v/--radius/--feather/--max-panel-fraction/
--reference-size, or programmatically via the `layout=` LayoutSettings argument.

Importable:
  from overlay_text import overlay, text_page
  overlay("page.png", "Once upon a time...", "bottom", "page-final.png")
  text_page("art.png", "Long text here.", "page-text.png")
"""

from __future__ import annotations
import argparse
import math
import sys
from dataclasses import dataclass, replace
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter, ImageFont

SKILL_DIR = Path(__file__).parent.parent
FONTS = {
    "reader": SKILL_DIR / "assets" / "fonts" / "Andika-Regular.ttf",
    "display": SKILL_DIR / "assets" / "fonts" / "PatrickHand-Regular.ttf",
}

# ---- Reference-unit layout defaults ----------------------------------------------
# Every length below is authored as pixels *at this reference size* and scaled by
# min(page_w, page_h) / reference_size at composite time — one uniform scalar, so
# type and padding grow together and an aspect-ratio change never changes type
# size. See docs/text-fitting.md.
REFERENCE_SIZE = 2048
DEFAULT_FONT_SIZE = 48          # measured to keep a 200-word page (STYLE_PRIMER's
                                 # documented ceiling) well inside max_panel_fraction
DEFAULT_MIN_FONT_SIZE = 22
DEFAULT_PAD_H = 40              # gap between text and panel's left/right edge
DEFAULT_PAD_V = 48              # gap between text block and panel's top/bottom edge
DEFAULT_RADIUS = 36
DEFAULT_FEATHER = 14            # 0 = hard edge
DEFAULT_MAX_PANEL_FRACTION = 0.9
LINE_LEADING = 8                # extra px of line spacing beyond the glyph bbox

# Horizontal text margin as fraction of image width — already resolution-
# independent, so it is not part of the reference-unit `layout` settings.
H_PAD_FRACTION = 0.05
# Top-placement gap from the frame, as fraction of image height. This is
# *placement*, not the boundary — it stays a module constant, out of `layout`.
# Deriving it from max_panel_fraction would couple two unrelated knobs and
# re-flow every top-placed page for no reason.
EDGE_MARGIN_FRACTION = 0.04
# Background panel alpha (0=transparent, 255=opaque) — unitless 0-255, nothing
# to scale, so it also stays outside `layout`.
BOX_ALPHA = 205


def _scale_len(v: float, scale: float, min_val: int = 0) -> int:
    return max(min_val, round(v * scale))


@dataclass(frozen=True)
class LayoutSettings:
    """The one box model's tunables, authored as pixels at `reference_size`
    (`max_panel_fraction` is already a fraction). `.scaled()` converts every
    length to actual page pixels via one uniform scalar. See docs/text-fitting.md.
    """

    reference_size: int = REFERENCE_SIZE
    font_size: int = DEFAULT_FONT_SIZE
    min_font_size: int = DEFAULT_MIN_FONT_SIZE
    pad_h: int = DEFAULT_PAD_H
    pad_v: int = DEFAULT_PAD_V
    radius: int = DEFAULT_RADIUS
    feather: int = DEFAULT_FEATHER
    max_panel_fraction: float = DEFAULT_MAX_PANEL_FRACTION

    def scaled(self, w: int, h: int) -> "LayoutSettings":
        """Return a copy with every reference-unit length scaled to (w, h).

        One uniform scalar for every length (min(w, h) / reference_size), so
        type and padding scale together and an aspect-ratio change never
        changes type size. font_size/min_font_size are floored at 1px (a 0px
        font crashes Pillow); feather has no such floor, so --feather 0 stays
        a hard edge at any resolution.
        """
        scale = min(w, h) / self.reference_size
        return replace(
            self,
            font_size=_scale_len(self.font_size, scale, min_val=1),
            min_font_size=_scale_len(self.min_font_size, scale, min_val=1),
            pad_h=_scale_len(self.pad_h, scale),
            pad_v=_scale_len(self.pad_v, scale),
            radius=_scale_len(self.radius, scale),
            feather=_scale_len(self.feather, scale),
        )


def _normalize_family(name: str) -> str:
    """Lowercase, keep only alphanumerics — so 'Patrick Hand' == 'PatrickHand'."""
    return "".join(c for c in name.lower() if c.isalnum())


def _bundled_font_path(name: str) -> Path | None:
    """Match a requested family name against a bundled .ttf in assets/fonts/.

    Bundled OFL fonts always win over a same-named system font, so 'Andika' /
    'Patrick Hand' resolve to the shipped files regardless of what's installed.
    """
    target = _normalize_family(name)
    fonts_dir = SKILL_DIR / "assets" / "fonts"
    for ttf in sorted(fonts_dir.glob("*.ttf")):
        stem = ttf.stem.lower().removesuffix("-regular")
        if _normalize_family(stem) == target:
            return ttf
    return None


def _resolve_font_ref(role: str, name: str | None = None) -> str:
    """Resolve a role + optional family name to a truetype reference (path or system name).

    Resolution order when an explicit family `name` is given:
      1. bundled asset matching the name (assets/fonts/)
      2. system-installed font (PIL searches OS font dirs by family name)
      3. bundled default for the role (reader -> Andika, display -> PatrickHand) + warning

    Rendering is rasterized to pixels, so using a system font (e.g. Arial) does not
    redistribute the font file. Unresolvable names never crash the render. Resolved
    once per overlay so the not-found warning fires at most once.
    """
    if name:
        bundled = _bundled_font_path(name)
        if bundled is not None:
            return str(bundled)
        for candidate in (name, f"{name}.ttf"):
            try:
                ImageFont.truetype(candidate, 12)  # probe OS font dirs
                return candidate
            except OSError:
                continue
        print(
            f"Warning: font {name!r} not found (no bundled asset, not a system font); "
            f"falling back to the bundled {role!r} font.",
            file=sys.stderr,
        )
    return str(FONTS.get(role, FONTS["reader"]))


def _load_font(font_ref: str, size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(font_ref, size)


def _wrap_paragraph(text: str, font: ImageFont.FreeTypeFont, max_width: int, draw: ImageDraw.ImageDraw) -> list[str]:
    """Greedy word-wrap of a single paragraph (no newlines) to max_width."""
    words = text.split()
    lines: list[str] = []
    current = ""
    for word in words:
        candidate = (current + " " + word).strip()
        bbox = draw.textbbox((0, 0), candidate, font=font)
        if bbox[2] - bbox[0] <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _word_wrap(text: str, font: ImageFont.FreeTypeFont, max_width: int, draw: ImageDraw.ImageDraw) -> list[str]:
    """Wrap story text to max_width, preserving the author's line structure.

    Every newline is a hard break, so a dialogue line stays on its own line; a blank
    line additionally yields an empty output line, keeping paragraphs visually apart.
    Runs of blank lines collapse to one spacer, and spacers never lead or trail the
    block. The returned list may therefore contain "" entries — callers must advance
    by one line height for them without drawing anything.
    """
    lines: list[str] = []
    for block in text.split("\n"):
        block = block.strip()
        if not block:
            if lines and lines[-1] != "":
                lines.append("")
            continue
        lines.extend(_wrap_paragraph(block, font, max_width, draw))
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def measure_text_block(
    text: str,
    font_ref: str,
    w: int,
    h: int,
    lay: LayoutSettings,
    max_box_h: int,
) -> tuple[int, list[str], int, int, int]:
    """Fit text to one panel sized from its own content.

    panel = text block (at lay.font_size) + padding — the box is derived from
    content, never configured. Font size shrinks in exactly one circumstance:
    the panel would otherwise exceed max_box_h, down to lay.min_font_size. That
    is a last-resort overflow guard, not a layout mechanism.

    `lay` must already be scaled to (w, h) via LayoutSettings.scaled() — this
    function does no unit conversion of its own.

    Returns (font_size, lines, line_h, box_h, dropped). Both the boundary check
    here and the draw loop in _compose() consume this single measurement —
    measuring the fit and the draw with two different formulas (as the old
    band/text-page fit loops did) is exactly the bug this replaces. `dropped`
    is the number of wrapped lines that don't fit even at lay.min_font_size
    (0 in the ordinary case) — the caller is responsible for reporting it.
    """
    scale = min(w, h) / lay.reference_size
    leading = _scale_len(LINE_LEADING, scale, min_val=1)
    max_text_w = int(w * (1 - 2 * H_PAD_FRACTION))
    dummy = ImageDraw.Draw(Image.new("RGBA", (w, h)))

    size = lay.font_size
    while True:
        font = _load_font(font_ref, size)
        lines = _word_wrap(text, font, max_text_w, dummy)
        bbox = dummy.textbbox((0, 0), "Ag", font=font)
        line_h = bbox[3] - bbox[1] + leading
        box_h = len(lines) * line_h + 2 * lay.pad_v
        if box_h <= max_box_h or size <= lay.min_font_size:
            break
        size = max(lay.min_font_size, size - 2)

    dropped = 0
    if box_h > max_box_h and line_h > 0:
        avail = max(0, max_box_h - 2 * lay.pad_v)
        fit_lines = avail // line_h
        if fit_lines < len(lines):
            dropped = len(lines) - fit_lines
            lines = lines[:fit_lines]
            box_h = len(lines) * line_h + 2 * lay.pad_v

    return size, lines, line_h, box_h, dropped


def _panel_mask(
    w: int, h: int, box: tuple[int, int, int, int], radius: int, alpha: int, feather: int
) -> Image.Image:
    """Build a full-canvas alpha mask with one blurred rounded rect painted on it.

    The blur is applied to the mask only, so the panel fades softly into the
    image instead of ending at a hard edge, while text (composited separately)
    stays crisp.
    """
    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).rounded_rectangle(box, radius=radius, fill=alpha)
    if feather > 0:
        mask = mask.filter(ImageFilter.GaussianBlur(feather))
    return mask


def _draw_text_lines(
    w: int,
    h: int,
    lines: list[str],
    font: ImageFont.FreeTypeFont,
    line_h: int,
    start_y: int,
    h_pad: int,
    max_text_w: int,
    align: str,
    color: str,
) -> Image.Image:
    """Draw every line handed to it onto its own transparent layer — no clipping
    loop. Any truncation was already decided once, by measure_text_block().

    All three alignments are defined against the text column [h_pad, w - h_pad],
    not raw canvas width, so 'right' lands its edge at w - h_pad regardless of
    padding.
    """
    text_layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(text_layer)
    text_color = (30, 30, 30, 255) if color == "dark" else (245, 245, 245, 255)
    y = start_y
    for line in lines:
        # "" is a paragraph spacer: it occupies a line but draws nothing.
        if line:
            line_w = draw.textlength(line, font=font)
            if align == "center":
                x = int(h_pad + (max_text_w - line_w) / 2)
            elif align == "right":
                x = int(w - h_pad - line_w)
            else:
                x = h_pad
            draw.text((x, y), line, font=font, fill=text_color)
        y += line_h
    return text_layer


def _compose(
    img: Image.Image,
    text: str,
    out_path: Path,
    font: str,
    font_name: str | None,
    color: str,
    box_alpha: int,
    align: str,
    layout: LayoutSettings,
    anchor: str,
    label: str,
) -> Path:
    """Shared panel-and-text compositor for both surfaces.

    anchor: 'top' | 'bottom' (band mode) | 'center' (text-page mode) — which
    edge the panel is pinned to, and the only thing that legitimately differs
    between band mode and text-page mode. See docs/text-fitting.md "Growth
    anchors".
    """
    w, h = img.size
    if not text.strip():
        img.convert("RGB").save(out_path)
        return out_path

    font_ref = _resolve_font_ref(font, font_name)
    lay = layout.scaled(w, h)

    edge_margin = int(h * EDGE_MARGIN_FRACTION)
    max_box_h = int(h * lay.max_panel_fraction)
    if anchor == "top":
        # A centred text page runs out of room top and bottom simultaneously; a
        # bottom-anchored band has one edge pinned and grows until it reaches
        # the top margin. Top placement is the one anchor with a second,
        # tighter ceiling: it must also leave the matching gap below.
        max_box_h = min(max_box_h, h - 2 * edge_margin)

    size, lines, line_h, box_h, dropped = measure_text_block(text, font_ref, w, h, lay, max_box_h)
    font_obj = _load_font(font_ref, size)

    max_text_w = int(w * (1 - 2 * H_PAD_FRACTION))
    h_pad = int(w * H_PAD_FRACTION)
    box_x0 = h_pad - lay.pad_h
    box_x1 = w - h_pad + lay.pad_h

    # Bottom placement anchors the panel flush to the image bottom (no gap); it
    # is drawn past the canvas edge so its rounded corners fall off-frame and
    # the bottom reads as a straight, full-bleed edge. Top keeps the edge
    # margin. Center floats with all four corners rounded.
    if anchor == "top":
        box_y0 = edge_margin
        panel_y1 = box_y0 + box_h
    elif anchor == "bottom":
        box_y0 = h - box_h
        panel_y1 = h + lay.radius
    else:  # center
        box_y0 = (h - box_h) // 2
        panel_y1 = box_y0 + box_h

    mask = _panel_mask(w, h, (box_x0, box_y0, box_x1, panel_y1), lay.radius, box_alpha, lay.feather)
    panel_rgb = (255, 255, 255) if color == "dark" else (30, 30, 30)
    panel = Image.new("RGBA", (w, h), panel_rgb + (0,))
    panel.putalpha(mask)
    img = Image.alpha_composite(img, panel)

    text_layer = _draw_text_lines(
        w, h, lines, font_obj, line_h, box_y0 + lay.pad_v, h_pad, max_text_w, align, color,
    )
    composed = Image.alpha_composite(img, text_layer)
    composed.convert("RGB").save(out_path)

    if dropped:
        # Warn and composite — never block a book assembly over one over-long
        # page. Stable "TEXT-OVERFLOW:" prefix so callers can grep stderr for it.
        print(
            f"TEXT-OVERFLOW: {label} — configured {lay.font_size}px, used {size}px, "
            f"{dropped} line(s) dropped",
            file=sys.stderr,
        )

    return out_path


def overlay(
    image_path: str | Path,
    text: str,
    placement: str,
    out_path: str | Path,
    font: str = "reader",
    color: str = "dark",
    box_alpha: int = BOX_ALPHA,
    font_name: str | None = None,
    align: str = "left",
    layout: LayoutSettings | None = None,
) -> Path:
    """
    Composite text onto an image in the top or bottom zone.

    The panel is sized from its content: panel = text block (at
    layout.font_size) + padding. Font size shrinks only if the panel would
    otherwise exceed layout.max_panel_fraction of the page — a last-resort
    overflow guard, not a layout mechanism. See docs/text-fitting.md.

    Args:
        image_path: Source PNG/JPG.
        text: Story text. Empty string = no overlay, just copies file.
        placement: 'top' or 'bottom'.
        out_path: Destination path.
        font: role 'reader' or 'display' — selects the bundled fallback font.
        color: 'dark' (near-black text on light panel) or 'light' (near-white text on dark
            panel). The semi-transparent panel behind the text adapts its base colour to
            match so the text stays legible.
        font_name: optional explicit family name (e.g. 'Arial'); resolved via bundled
            asset -> system font -> bundled role fallback. None = use the role font.
        align: 'left' (default), 'center', or 'right' — horizontal alignment of each line.
        layout: LayoutSettings overriding the reference-unit defaults. None = defaults.

    Returns:
        Path to written file.
    """
    out_path = Path(out_path)
    image_path = Path(image_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(image_path).convert("RGBA")
    anchor = "top" if placement == "top" else "bottom"
    return _compose(
        img, text, out_path, font, font_name, color, box_alpha, align,
        layout or LayoutSettings(), anchor, out_path.name,
    )


def text_page(
    image_path: str | Path,
    text: str,
    out_path: str | Path,
    font: str = "reader",
    color: str = "dark",
    box_alpha: int = BOX_ALPHA,
    font_name: str | None = None,
    align: str = "left",
    canvas_from: str | Path | None = None,
    layout: LayoutSettings | None = None,
) -> Path:
    """
    Render a full text page for long story mode.

    image_path is a purpose-made background (generated by the render stage with a
    reserved low-detail central section); it is used as-is — no blur, no wash. When
    canvas_from is set, the background is scale-to-cover + center-cropped to match the
    canvas_from image's dimensions, so the text page always matches its art page.

    Text sits on a vertically centered, feathered semi-transparent panel, sized
    from its own content exactly as overlay() sizes a band — both surfaces
    share the one box model (see _compose()), differing only in growth anchor.

    Args:
        image_path: The background image.
        text: Story text. Empty string = plain background, no panel.
        out_path: Destination path.
        font: role 'reader' or 'display'.
        color: 'dark' (near-black text on light panel) or 'light' (near-white text on dark
            panel). The semi-transparent panel behind the text adapts its base colour.
        box_alpha: Panel opacity 0-255.
        font_name: Explicit font family; resolved via bundled asset -> system font -> fallback.
        align: 'left', 'center', or 'right'.
        canvas_from: When set, open this image to get target (W, H); scale-crop image_path to fit.
        layout: LayoutSettings overriding the reference-unit defaults. None = defaults.

    Returns:
        Path to written file.
    """
    out_path = Path(out_path)
    image_path = Path(image_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    img = Image.open(image_path).convert("RGBA")
    w, h = img.size

    if canvas_from is not None:
        # Get target dims from canvas_from, then scale-to-cover + center-crop the
        # background to those dims so the text page always matches its art page.
        ref = Image.open(canvas_from)
        tw, th = ref.size
        scale = max(tw / w, th / h)
        new_w = math.ceil(w * scale)
        new_h = math.ceil(h * scale)
        img = img.resize((new_w, new_h), Image.LANCZOS)
        x0 = (new_w - tw) // 2
        y0 = (new_h - th) // 2
        img = img.crop((x0, y0, x0 + tw, y0 + th))

    return _compose(
        img, text, out_path, font, font_name, color, box_alpha, align,
        layout or LayoutSettings(), "center", out_path.name,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Overlay story text onto a page image.")
    parser.add_argument("--image", required=True, help="Source image path")
    parser.add_argument("--text", required=True, help="Text to overlay")
    parser.add_argument("--placement", choices=["top", "bottom"], default="bottom")
    parser.add_argument("--out", required=True, help="Output image path")
    parser.add_argument("--font", choices=["reader", "display"], default="reader",
                        help="Font role; selects the bundled fallback font")
    parser.add_argument("--font-name", default=None,
                        help="Explicit font family (e.g. 'Arial'); resolved via bundled asset "
                             "-> system font -> bundled role fallback")
    parser.add_argument("--color", choices=["dark", "light"], default="dark")
    parser.add_argument("--align", choices=["left", "center", "right"], default="left",
                        help="Horizontal text alignment (default left)")
    parser.add_argument("--box-alpha", type=int, default=BOX_ALPHA,
                        help=f"Panel opacity 0-255 (default {BOX_ALPHA}; lower = more transparent)")
    # Layout — the one box model's reference-unit settings (see docs/text-fitting.md).
    # All are pixels at --reference-size, scaled by min(page_w, page_h) / reference-size
    # at composite time; --max-panel-fraction is already a fraction.
    parser.add_argument("--reference-size", type=int, default=REFERENCE_SIZE,
                        help=f"Declared reference size in px (default {REFERENCE_SIZE}); "
                             "every other layout flag is authored at this size")
    parser.add_argument("--font-size", type=int, default=DEFAULT_FONT_SIZE,
                        help=f"Font size at --reference-size (default {DEFAULT_FONT_SIZE}px)")
    parser.add_argument("--min-font-size", type=int, default=DEFAULT_MIN_FONT_SIZE,
                        help=f"Overflow-guard floor at --reference-size (default {DEFAULT_MIN_FONT_SIZE}px)")
    parser.add_argument("--pad-h", type=int, default=DEFAULT_PAD_H,
                        help=f"Panel padding left/right at --reference-size (default {DEFAULT_PAD_H}px)")
    parser.add_argument("--pad-v", type=int, default=DEFAULT_PAD_V,
                        help=f"Panel padding top/bottom at --reference-size (default {DEFAULT_PAD_V}px)")
    parser.add_argument("--radius", type=int, default=DEFAULT_RADIUS,
                        help=f"Panel corner radius at --reference-size (default {DEFAULT_RADIUS}px)")
    parser.add_argument("--feather", type=int, default=DEFAULT_FEATHER,
                        help=f"Edge blur radius at --reference-size (default {DEFAULT_FEATHER}px; 0 = hard edge)")
    parser.add_argument("--max-panel-fraction", type=float, default=DEFAULT_MAX_PANEL_FRACTION,
                        help=f"Boundary: most of the page height a panel may cover before the "
                             f"overflow guard shrinks the font (default {DEFAULT_MAX_PANEL_FRACTION})")
    # Long story mode — text-page rendering.
    parser.add_argument("--text-page", action="store_true",
                        help="Render a text-only page (long story mode): centered panel over a "
                             "purpose-made background image (used as-is, no blur/wash). "
                             "Ignores --placement.")
    parser.add_argument("--canvas-from", default=None, metavar="PATH",
                        help="(--text-page only) Open this image to get target W×H; scale-crop "
                             "--image to those dims so text page matches art page dimensions.")
    args = parser.parse_args()

    layout = LayoutSettings(
        reference_size=args.reference_size,
        font_size=args.font_size,
        min_font_size=args.min_font_size,
        pad_h=args.pad_h,
        pad_v=args.pad_v,
        radius=args.radius,
        feather=args.feather,
        max_panel_fraction=args.max_panel_fraction,
    )

    if args.text_page:
        result = text_page(
            args.image, args.text, args.out, args.font, args.color,
            box_alpha=args.box_alpha, font_name=args.font_name,
            align=args.align, canvas_from=args.canvas_from, layout=layout,
        )
    else:
        result = overlay(
            args.image, args.text, args.placement, args.out, args.font, args.color,
            box_alpha=args.box_alpha, font_name=args.font_name,
            align=args.align, layout=layout,
        )
    print(f"Saved: {result}")


if __name__ == "__main__":
    main()
